version: '3'

services:
### Task manager ###############################################
    task-manager:
      build:
        context: ../
        dockerfile: docker/Dockerfile
      networks:
        - task_manger_network
      container_name: task-manager
      environment:
        - ENVIRONMENT=DEVELOPMENT
        - SQLALCHEMY_DATABASE_URI=mysql://root:bjs123@host.docker.internal:3306/task_manager
      volumes: ['../../task_manager:/app']
      ports:
        - '4501:5001'

networks:
  task_manger_network:
    external:
      name: task_manger_network
